### ISSUE TITLE
Text size and theme

### ISSUE THREAD

**Issue by llctrautmann** [franneck94/vscode-rust-config#1]
This is less of an issue and more of a general question. Would it be possible to set the default text size and IDE theme for every config file creation? The extension is great, but I need to change the editor, terminal text size value and theme for each new Rust project, and there has to be a more efficient way than doing it manually every time. Any suggestions?

Sorry if this is in the wrong category.

**Comment by franneck94** [comment]
Hi, i removed the font sizes now from the local setting files.
Then you can just set it for your whole system to have the same font size in every workspace.

Is it then solved for you?

**Comment by llctrautmann** [comment]
This should work, I think. I will reinstall rust config and double check if running `generate rust config` will still set the the editor font size in the setting.json file. Thanks for the quick answer and awesome extension!

**Comment by llctrautmann** [comment]
Unfortunately, the behaviour is still the same. When the settings.json file is created with `Rust Config: generate ...` these variables override the global font size settings: 

    "editor.fontSize": 21,
    "terminal.integrated.fontSize": 20,
    "markdown.preview.fontSize": 21,

If it is too much of a nuisance for you right now, please don't bother. I can simply delete the respective code lines from each project's settings file. But I am working on your rust course at the moment, and for each new topic, my IDE theme and font is changed, so I thought maybe removing these settings might enhance the user experience.

**Comment by franneck94** [comment]
So for me in version 1.2.0 it does not haev the font sizes anymore

**Comment by franneck94** [comment]
If it is still not correct, please com back to me

**Comment by llctrautmann** [comment]
Sorry for the long response time. I checked it. It is now working. Thanks very much!
